"""add roles table

Revision ID: 45fe026e4310
Revises: 6808457123ce
Create Date: 2026-06-19 18:04:55.045693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fe026e4310'
down_revision: Union[str, Sequence[str], None] = '6808457123ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.execute("INSERT INTO roles VALUES (1, 'admin'), (2, 'user')")
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
